name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install Monogame
      run: dotnet new --install "MonoGame.Templates.CSharp"
    - name: Install Monogame Framework DesktopGL
      run: dotnet add ./Iterex/Iterex.csproj package MonoGame.Framework.DesktopGL --prerelease
    - name: Install Monogame Content Builder
      run: dotnet add ./Iterex/Iterex.csproj package MonoGame.Content.Builder.Task --prerelease
    - name: Install NUnit
      run:  dotnet add ./Iterex.Tests/Iterex.Tests.csproj package NUnit --prerelease
    - name: Install Moq
      run: dotnet add ./Iterex.Tests/Iterex.Tests.csproj package Moq --prerelease
    - name: Restore dependencies
      run: dotnet restore ./Iterex/Iterex.csproj
    - name: Build
      run: dotnet clean ; dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
