name: Iterex CI

on:
  push:
    branches: 
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install NUnit
      run:  dotnet add ./Iterex.Tests/Iterex.Tests.csproj package NUnit --version 3.13.2
    - name: Install Moq
      run: dotnet add ./Iterex.Tests/Iterex.Tests.csproj package Moq --version 4.16.1
    - name: Restore dependencies
      run: dotnet restore ./Iterex/Iterex.csproj
    - name: Build
      run: dotnet clean ; dotnet build --no-restore
    - name: Test
      run: dotnet test