name: .NET

on:
  push:
    branches: 
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install NUnit
      run:  dotnet add ./Iterex.Tests/Iterex.Tests.csproj package NUnit --version 3.13.2
    - name: Install Moq
      run: dotnet add ./Iterex.Tests/Iterex.Tests.csproj package Moq --version 4.16.1
    - name: Restore dependencies
      run: dotnet restore ./Iterex/Iterex.csproj
    - name: Build
      run: dotnet clean ; dotnet build --no-restore
    - name: Test
      run: dotnet test

name: Format check on push
on:
  push:
    branches: 
    - '*'
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1
        
name: Generate Documentation
on:
  push:
    branches: 
    - '*'
jobs:
  Doxygenize:
    runs-on: ubuntu-latest
    steps:
     - name: Doxygenize
       uses: langroodi/doxygenize@v1.4
       with:
            ghpagesbranch: 'main'