name: .NET

on:
  push:
    branches: [ main, ci-branch ]
  pull_request:
    branches: [ main, ci-branch ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install NUnit
      run:  dotnet add ./Iterex.Tests/Iterex.Tests.csproj package NUnit --prerelease
    - name: Install Moq
      run: dotnet add ./Iterex.Tests/Iterex.Tests.csproj package Moq --prerelease
    - name: Restore dependencies
      run: dotnet restore ./Iterex/Iterex.csproj
    - name: Build
      run: dotnet build ./Iterex/Iterex.csproj --no-restore
    - name: Test
      run: dotnet test ./Iterex/Iterex.csproj --no-build --verbosity normal
