name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install Monogame
      run: dotnet new --install "MonoGame.Templates.CSharp"
    - name: Install Monogame Content Builder
      run: dotnet add ./Iterex/Iterex.csproj package MonoGame.Content.Builder.Linux --version 3.7.0.8
    - name: Restore dependencies
      run: dotnet restore ./Iterex/Iterex.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
