name: .NET

on:
  push:
    branches: 
	- "**"
  pull_request:
    branches:
	- "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install Monogame
      run: dotnet new --install "MonoGame.Templates.CSharp"
    - name: Install Monogame Framework DesktopGL
      run: dotnet add ./Iterex/Iterex.csproj package MonoGame.Framework.DesktopGL --prerelease
    - name: Install Monogame Content Builder
      run: dotnet add ./Iterex/Iterex.csproj package MonoGame.Content.Builder.Task --prerelease
    - name: Install NUnit
      run:  dotnet add ./Iterex.Tests/Iterex.Tests.csproj package NUnit --prerelease
    - name: Install Moq
      run: dotnet add ./Iterex.Tests/Iterex.Tests.csproj package Moq --prerelease
    - name: Build
      run: dotnet clean ; dotnet build  ./Iterex/Iterex.csproj --no-restore
    - name: Test
      run: dotnet test ./Iterex.Tests/Iterex.Tests.csproj --no-build --verbosity normal
