name: Generate Documentation
on: push
jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.3.1