name: Generate Documentation
on: push
jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
     - name: "Doxygen"
       run: |
         sudo apt-get install -y doxygen
         ls -ls
         doxygen Iterex/Doxyfile
