name: Generate Documentation
on: push
jobs:
  Doxygenize:
    runs-on: ubuntu-latest
    steps:
     - name: Doxygenize
       uses: langroodi/doxygenize@v1.4
       with:
            ghpagesbranch: 'main'
            doxygenconf: './Iterex/Doxyfile'
            htmloutput: './Iterex/docs'
            ghpagesdir: './Iterex/docs'