name: Generate Documentation
on: push
jobs:
  Doxygenize:
    runs-on: ubuntu-latest
    steps:
     - name: Doxygen
       uses: mattnotmitt/doxygen-action@v1
       with:
        working-directory: 'Iterex/'