name: Generate Documentation
on: push
jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Doxygenize
        uses: langroodi/doxygenize@v1.4
        with:
            ghpagesbranch: 'main'